### ISSUE TITLE
host logging not working

### ISSUE THREAD

**Issue by vijaykhemka** [openbmc/phosphor-hostlogger#1]
@andrew: With new design changes in obmc-console, host loggers is not craeting any logs. I saw that there is a change in socket path in obmc-console code. As it has been changed from "\0obmc-console" to "obmc-console". This may need to be revised as per new design also support multi host.

**Comment by amboar** [comment]
@vijaykhemka you're after me, not the other Andrew :)

**Comment by artemsen** [comment]
Actually, the latest version of obmc-console [still uses \0](https://github.com/openbmc/obmc-console/blob/d802b11942abc8a4641976e70d567758ef0bbd58/console-socket.c#L51) in the socket path.
I assume that the problem is in multi-host configuration, which is still not supported by Hostlogger.
@vijaykhemka, do you use multi host in obmc-console?
Anyway, I agree that Hostlogger needs this feature.

**Comment by vijaykhemka** [comment]
I have both multi host and single host platform but currently I am testing in single host and it is not working. I don’t see any directory  /var/lib/obmc/hostlogs on my target.  I see hostlogger is running. I see logs on /var/log/obmc-console.log which is getting created by obmc-console.

**Comment by artemsen** [comment]
@vijaykhemka, do you use the "socket-id" option for the obmc-console? Or you have default (empty) socket id in single host setup?
Also, please try to force save the hostlogger's buffer after:
```
bmc# busctl call \
            xyz.openbmc_project.HostLogger /xyz/openbmc_project/HostLogger \
            xyz.openbmc_project.HostLogger Flush
```
I just want to find out where the problem is.

**Comment by vijaykhemka** [comment]
@artemsen, I use default (no socket id) in single host case. And I see log file after flushing it.

**Comment by artemsen** [comment]
I think the problem is in D-Bus watcher. Hostlogger monitors state for hardcoded object `/xyz/openbmc_project/state/host0`. 
@vijaykhemka, could you check this? You can get the object path with busctl: `busctl tree xyz.openbmc_project.State.Host`.

**Comment by vijaykhemka** [comment]
root@tiogapass:~# busctl tree xyz.openbmc_project.State.Host
└─/xyz
  └─/xyz/openbmc_project
    ├─/xyz/openbmc_project/chassis
    │ └─/xyz/openbmc_project/chassis/buttons
    │   ├─/xyz/openbmc_project/chassis/buttons/nmi
    │   ├─/xyz/openbmc_project/chassis/buttons/power
    │   └─/xyz/openbmc_project/chassis/buttons/reset
    ├─/xyz/openbmc_project/control
    │ └─/xyz/openbmc_project/control/host0
    │   └─/xyz/openbmc_project/control/host0/restart_cause
    └─/xyz/openbmc_project/state
      ├─/xyz/openbmc_project/state/chassis0
      ├─/xyz/openbmc_project/state/host0
      └─/xyz/openbmc_project/state/os

**Comment by vijaykhemka** [comment]
I tried host power off and on. But I only see files created after flushing using command you gave

**Comment by artemsen** [comment]
I am out of ideas. Unfortunately, I can't reproduce the issue on my hardware (OpenPOWER systems).
I have started refactoring of the project to add multi-host support, may be I will find something during this work.

**Comment by artemsen** [comment]
@vijaykhemka, could you check the current revision?
The latest version of the project supports multi-host mode and there are some changes about D-Bus monitoring.

**Comment by vijaykhemka** [comment]
Sure, I will look into this.

**Comment by artemsen** [comment]
x86 based systems should use `/xyz/openbmc_project/state/os` for host state monitoring:
https://github.com/openbmc/phosphor-hostlogger#custom-object-for-host-state-monitoring
